# Generated by Django 4.2.9 on 2024-01-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemandplants',
            name='image',
            field=models.URLField(max_length=2048),
        ),
    ]
