# Generated by Django 4.2.9 on 2024-01-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_gemandplants_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stars', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('date_added', models.DateField()),
                ('date_updated', models.DateField()),
            ],
        ),
    ]
