# Generated by Django 4.2.9 on 2024-01-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date_purchased',
            field=models.DateTimeField(default='2023-01-01 00:00'),
        ),
    ]
