# Generated by Django 4.2.9 on 2024-01-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_purchase_date_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_purchased',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
