# Generated by Django 4.2.9 on 2024-01-25 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_purchase_comment_purchase_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='stars',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('stars', models.IntegerField()),
                ('comment', models.TextField()),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
