# Generated by Django 4.2.9 on 2024-01-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_purchase_comment_remove_purchase_stars_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='purchase',
            field=models.CharField(max_length=100),
        ),
    ]
