# Generated by Django 4.2.9 on 2024-01-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_review_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='purchase',
            field=models.CharField(max_length=300),
        ),
    ]
