# Generated by Django 4.2.9 on 2024-01-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_review_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='purchase',
        ),
    ]
