# Generated by Django 4.2.9 on 2024-01-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_review_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
