# Generated by Django 4.2.9 on 2024-01-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_purchase_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_reviewed',
            field=models.DateTimeField(default=None),
        ),
    ]
