# Generated by Django 4.2.9 on 2024-01-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_review_date_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_reviewed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
