# Generated by Django 4.2.9 on 2024-01-26 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_review_date_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('location', models.CharField(blank=True, choices=[('AR', 'Artigas'), ('CA', 'Canelones'), ('CL', 'Cerro Largo'), ('CO', 'Colonia'), ('DU', 'Durazno'), ('FS', 'Flores'), ('FD', 'Florida'), ('LA', 'Lavalleja'), ('MA', 'Maldonado'), ('MO', 'Montevideo'), ('PA', 'Paysandú'), ('RN', 'Río Negro'), ('RV', 'Rivera'), ('RO', 'Rocha'), ('SA', 'Salto'), ('SJ', 'San José'), ('SO', 'Soriano'), ('TA', 'Tacuarembó'), ('TT', 'Treinta y Tres')], max_length=2)),
                ('avatar', models.URLField(blank=True, default='https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
